# ======================
# BUILD STAGE
# ======================
FROM maven:3.9.9-eclipse-temurin-21 AS build
WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline

COPY src ./src
RUN mvn clean package -DskipTests

# ======================
# RUNTIME STAGE
# ======================
FROM eclipse-temurin:21-jre
WORKDIR /app

COPY --from=build /app/target/notProjesi-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8085
ENTRYPOINT ["java","-jar","app.jar"]
